# Generated by Django 3.2 on 2024-11-18 19:52

import bodegaAliceapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('idDistribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=15)),
                ('fechaDespacho', models.DateField()),
                ('fechaRecepcion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('fechaFacturacion', models.DateField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=15, validators=[bodegaAliceapp.models.validacion_positivo])),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5, validators=[bodegaAliceapp.models.validacion_positivo])),
                ('descuentoTotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[bodegaAliceapp.models.validacion_positivo])),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='bodegaAliceapp.distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('denominacionOrigen', models.CharField(max_length=50)),
                ('cantidadProducto', models.IntegerField(validators=[bodegaAliceapp.models.validacion_positivo])),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('distribuidores', models.ManyToManyField(blank=True, null=True, related_name='productos', to='bodegaAliceapp.Distribuidor')),
                ('facturas', models.ManyToManyField(blank=True, null=True, related_name='productos', to='bodegaAliceapp.Factura')),
            ],
        ),
    ]
